// "use client"
import Script from "next/script";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/component/Header";
import Footer from "@/component/Footer";
import "bootstrap/dist/css/bootstrap.min.css"
import '@fortawesome/fontawesome-svg-core/styles.css';
import '@fortawesome/fontawesome-free/css/all.min.css';
import { config } from '@fortawesome/fontawesome-svg-core';
import '../../public/revolution/css/settings.css';
import '../../public/revolution/css/layers.css';
import '../../public/revolution/css/navigation.css';
import 'animate.css';
import "./custom.scss";
// import "./globals.css";
// import "../../public/css/responsive.css";
import BootstrapClient from "@/component/bootstrap-client";
import Preloader from "@/component/preloader";
import AosClient from "@/component/AosClient";
// import { usePathname } from "next/navigation";
import Adminheader from "@/component/Adminheader";
import Adminmenu from "@/component/Adminmenu";
config.autoAddCss = false;
import { headers } from 'next/headers'
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({ children }) {


  //const path = usePathname();
  const headersList = await headers();
  const path = headersList.get('x-pathname');
  let Details = {};
  let pagelist = [];
  if (path !== '/admin') {


    try {
      const res = await fetch(`${process.env.NEXT_PUBLIC_BASE_URL}/details`, {
        cache: "no-store",
        method: 'GET'
      });

      if (!res.ok) throw new Error(`Failed to fetch: ${res.status}`);
      const response = await res.json();
      if (response.status) {
        Details = response.details;
        pagelist=response.pagelist
      
      }

    } catch (error) {
      console.error("Fetch error:", error);
    }
  }
  return (
    <>
      {path.substr(0, 6) !== '/admin' ?

        path === '/login' ? <html lang="en" data-layout="vertical" data-topbar="light" data-sidebar="dark" data-sidebar-size="lg" data-sidebar-image="none" data-preloader="disable" data-theme="default" data-theme-colors="default" data-sidebar-visibility="show" data-layout-style="default" data-bs-theme="light" data-layout-width="fluid" data-layout-position="fixed" data-body-image="none">
          <head>

            <title>Admin | login</title>
            <link rel="icon" type="image/ico" href="/assets/img/favicon.ico" />
            <link rel="stylesheet" href="/assets1/libs/aos/aos.css" />
            {/* Layout config Js */}
            {/* Bootstrap Css */}
            <link href="/assets1/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
            {/* Icons Css */}
            <link href="/assets1/css/icons.min.css" rel="stylesheet" type="text/css" />
            {/* App Css*/}
            <link href="/assets1/css/app.min.css" rel="stylesheet" type="text/css" />
            {/* custom Css*/}
            <link href="/assets1/css/custom.min.css" rel="stylesheet" type="text/css" />


          </head>
          <body>

            {children}
            <Script src="/assets1/libs/bootstrap/js/bootstrap.bundle.min.js" />
            <Script src="/assets1/libs/simplebar/simplebar.min.js" />
            <Script src="/assets1/libs/node-waves/waves.min.js" />
            <Script src="/assets1/libs/feather-icons/feather.min.js" />
            <Script src="/assets1/js/pages/plugins/lord-icon-2.1.0.js" />
            <Script src="/assets1/js/plugins.js" />
            <Script src="/assets1/libs/aos/aos.js" />
            <Script src="/assets1/libs/prismjs/prism.js" />
            <Script src="/assets1/js/pages/animation-aos.init.js" />
            <Script src="/assets1/js/app.js" />
            <Script src="/assets1/libs/particles.js/particles.js" />
            <Script src="/assets1/js/pages/particles.app.js" />
            <Script src="/assets1/js/pages/password-addon.init.js" />



          </body>
        </html> : <html lang="en">
          <head>
            {/* custom Css*/}
            <link href="/css/frontend.css" rel="stylesheet" type="text/css" />
            <link href="/css/responsive.css" rel="stylesheet" type="text/css" />
            <link href="/assets/css/custom.css" rel="stylesheet" type="text/css" />


          </head>
          <body className={`${geistSans.variable} ${geistMono.variable}`}>
            {/* Load jQuery and Revolution Slider scripts */}
            <Script src="https://code.jquery.com/jquery-3.6.0.min.js" strategy="beforeInteractive" />
            <Script src="/revolution/js/jquery.themepunch.revolution.min.js" strategy="beforeInteractive" />
            <Script src="/revolution/js/jquery.themepunch.tools.min.js" strategy="beforeInteractive" />
            <Script src="/revolution/js/extensions/revolution.extension.actions.min.js" strategy="beforeInteractive" />
            <Script src="/revolution/js/extensions/revolution.extension.carousel.min.js" strategy="beforeInteractive" />
            <Script src="/revolution/js/extensions/revolution.extension.kenburn.min.js" strategy="beforeInteractive" />
            <Script src="/revolution/js/extensions/revolution.extension.layeranimation.min.js" strategy="beforeInteractive" />
            <Script src="/revolution/js/extensions/revolution.extension.migration.min.js" strategy="beforeInteractive" />
            <Script src="/revolution/js/extensions/revolution.extension.navigation.min.js" strategy="beforeInteractive" />
            <Script src="/revolution/js/extensions/revolution.extension.parallax.min.js" strategy="beforeInteractive" />
            <Script src="/revolution/js/extensions/revolution.extension.slideanims.min.js" strategy="beforeInteractive" />
            <Script src="/revolution/js/extensions/revolution.extension.video.min.js" strategy="beforeInteractive" />

            <main className="page-wrapper">
              <Preloader />
              <AosClient />

              <Header Details={Details} pagelist={pagelist}/>

              {/* Render the page content */}
              {children}

              <Footer Details={Details} />
            </main>

            {/* Bootstrap Client Component */}
            <BootstrapClient />
          </body>
        </html> : <html lang="en" data-layout="vertical" data-topbar="light" data-sidebar="dark" data-sidebar-size="lg" data-sidebar-image="none" data-preloader="disable" data-theme="default" data-theme-colors="default" data-sidebar-visibility="show" data-layout-style="default" data-bs-theme="light" data-layout-width="fluid" data-layout-position="fixed" data-body-image="none">
          <head>

            <link rel="icon" type="image/png" href="/assets/img/favicon.ico" />
            <link rel="stylesheet" href="/assets1/libs/aos/aos.css" />
            {/* Layout config Js */}
            {/* Bootstrap Css */}
            <link href="/assets1/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
            {/* Icons Css */}
            <link href="/assets1/css/icons.min.css" rel="stylesheet" type="text/css" />
            {/* App Css*/}
            <link href="/assets1/css/app.min.css" rel="stylesheet" type="text/css" />
         
            {/* custom Css*/}
            <link href="/assets1/css/custom.min.css" rel="stylesheet" type="text/css" />
            <Script src="/assets1/js/layout.js" />


          </head>
          <body cz-shortcut-listen="true" data-aos-easing="ease-out-back" data-aos-duration="1000" data-aos-delay="0">

            <div id="layout-wrapper">

              <Adminheader />
              {children}
              <Adminmenu />
            </div>
            <Script src="/assets1/libs/bootstrap/js/bootstrap.bundle.min.js" />
            <Script src="/assets1/libs/simplebar/simplebar.min.js" />
            <Script src="/assets1/libs/node-waves/waves.min.js" />
            <Script src="/assets1/libs/feather-icons/feather.min.js" />
            <Script src="/assets1/js/pages/plugins/lord-icon-2.1.0.js" />
            <Script src="/assets1/js/plugins.js" />
            <Script src="/assets1/libs/aos/aos.js" />
            <Script src="/assets1/libs/prismjs/prism.js" />
            <Script src="/assets1/js/pages/animation-aos.init.js" />
            <Script src="/assets1/js/app.js" />



          </body>
        </html>}
    </>
  );
}
